#!/bin/bash
##
# $ source kluster/etc/config
##

clear

export DOCKER_HOST=unix:///home/rik/.docker/desktop/docker.sock
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo
echo "Kluster Tooling:"
echo
echo "    docker  : $(wiv docker)"
echo "    minikube: $(wiv minikube | head -1)"
echo "    kubectl : $(wiv kubectl)"
echo "    helm    : $(wiv helm | egrep -o Version..v[^,]+)"
echo "    http    : $(wiv http)"
echo "    jq      : $(wiv jq)"
echo "    yq      : $(wiv yq)"
echo

source $BASE/script/etc/engine
