#!/bin/bash
##
# $ source kluster/etc/config
##

export DOCKER_HOST=unix:///home/rik/.docker/desktop/docker.sock
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

echo "Kluster Tooling:

    docker  : $(wiv docker)
    minikube: $(wiv minikube | head -1)
    kubectl : $(wiv kubectl)
    helm    : $(wiv helm | egrep -o Version..v[^,]+)
    http    : $(wiv http)
    jq      : $(wiv jq)
    yq      : $(wiv yq)
"
docker_start
minikube_start
tunnel_start
monitor_start
echo "Kluster Engine:

    Docker  : $(docker_status)
    Minikube: $(minikube_status)
    Tunnel  : $(tunnel_status)
    Monitor : $(monitor_status)
"
