apiVersion: v1
kind: Service

metadata:
  name: wss

spec:
  type: LoadBalancer
  ports:
    - port: {{.Values.serverPort}}
      targetPort: {{.Values.serverPort}}
      nodePort: {{.Values.serverPort}}
  selector:
    {{.Values.selectorKey}}: {{.Values.selectorGem}}
