apiVersion: v1
kind: Service

metadata:
  name: wss

spec:
  type: LoadBalancer
  ports:
    - nodePort: {{.Values.port.node}}
      port: {{.Values.port.rear}}
      targetPort: {{.Values.port.target}}
  selector:
    {{.Values.selectorKey}}: {{.Values.selectorGem}}
