apiVersion: v1
kind: Service

metadata:
  name: wss

spec:
  type: LoadBalancer
  ports:
    - nodePort: {{.Values.port.front}}
      port: {{.Values.port.back}}
      targetPort: {{.Values.port.back}}
  selector:
    {{.Values.selectorKey}}: {{.Values.selectorGem}}
