apiVersion: v1
kind: Service

metadata:
  name: wss

spec:
  type: NodePort
  ports:
    - port: {{.Values.serverPort}}
      targetPort: {{.Values.serverPort}}
      nodePort: {{.Values.serverPort}}
  selector:
    selectable: wsp
