#!/bin/bash
##
# $ source etc/config
##

clear

export DOCKER_HOST=unix://$HOME/.docker/desktop/docker.sock
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
$BASE/container/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo
echo "Container Tooling:"
echo
echo "    docker: $(wiv docker)"
echo "    http  : $(wiv http)"
echo "    jq    : $(wiv jq)"
echo

source $BASE/script/etc/engine
