#!/bin/bash
##
# $ source etc/config
##

export DOCKER_HOST=unix:///home/rik/.docker/desktop/docker.sock
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
$BASE/container/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
systemctl start docker-desktop.service --user
echo "Container Tooling

    docker  : $(wiv docker)
    http    : $(wiv http)
    jq      : $(wiv jq)

"
