#!/bin/bash
##
# $ source etc/config
##

export DOCKER_HOST=unix://$HOME/.docker/desktop/docker.sock
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
$BASE/container/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo "Container Tooling:

    docker: $(wiv docker)
    http  : $(wiv http)
    jq    : $(wiv jq)
"
systemctl start docker-desktop.service --user
# sleep 3
echo "Container Engine:

    Docker: $(systemctl is-active docker-desktop.service --user)
"
