apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{.Values.serverColour}}

spec:
  replicas: 3
  selector:
    matchLabels:
      colour: {{.Values.serverColour}}
  template:
    metadata:
      name: wsp
      labels:
        colour: {{.Values.serverColour}}
        mixture: {{.Values.serverMixture}}
    spec:
      containers:
        - name: wsc
          image: rik911/web-server-container:0.2.1
          args:
            - --colour={{.Values.serverColour}}
          env:
            - name: SERVER_PORT
              value: "{{.Values.serverPort}}"
          ports:
            - containerPort: {{.Values.serverPort}}
