apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{.Values.serverColour}}

spec:
  replicas: 3
  selector:
    matchLabels:
      colour: {{.Values.serverColour}}
  template:
    metadata:
      name: wsp
      labels:
        colour: {{.Values.serverColour}}
        mixture: {{.Values.serverMixture}}
    spec:
      containers:
        - name: wsc
          image: {{.Values.image.name}}
          env:
            - name: SERVER_PORT
              value: "{{.Values.port.application}}"
            - name: COLOUR
              value: {{.Values.serverColour}}
          ports:
            - containerPort: {{.Values.port.container}}
