#!/bin/bash
##
# $ source etc/config
##

export JAVA_HOME=$HOME/studio/program/jdk-17.0.2
export MAVEN_HOME=$HOME/studio/program/apache-maven-3.8.5
export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$JAVA_HOME/bin:\
$MAVEN_HOME/bin:\
$BASE/loader/bin:\
$BASE/script/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo "Application Tooling

    java: $(wiv java | head -1)
    mvn : $(wiv mvn | head -1)
    http: $(wiv http)
"
