#!/bin/bash
##
# $ script/check-tooling
##

which_version () { program=$1
    if which $program &>/dev/null
    then $program --version
    else echo "not found"
    fi
}

echo "
    java: $(which_version java | head -1)
    mvn : $(which_version mvn | head -1)
    http: $(which_version http)
    jq  : $(which_version jq)
"
