#!/bin/bash
##
# $ source loader/etc/config
##

clear

export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo
echo "Loader Tooling:"
echo
echo "    http: $(wiv http)"
echo "    jq  : $(wiv jq)"
echo
