#!/bin/bash
##
# $ source etc/config
##

export BASE=$(dirname "$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[*]}")")")")

export PATH=.:\
$BASE/loader/bin:\
$BASE/script/bin:\
/usr/local/bin:\
/usr/bin:\
/bin

clear
echo "Loader Tooling

    http: $(wiv http)
    jq  : $(wiv jq)
"
